### ISSUE TITLE
about H0-AT_Centromere_histograms_summary.txt

### ISSUE THREAD

**Issue by frwjo** [celphin/RepeatOBserverV1#6]
Hi;
    thank you for your softwore ; my genome has much Retrotransposon，so, my genome position is not clear.But I still get this txt file,and this file give me the Centromere,It is that right?If this is right Centromere,could I get the Centromere's rnage rather than dot?
Best!

**Comment by celphin** [comment]
Hi, The approximate centromere position is given in the histograms text file (with about a 2Mbp precision - since the histograms use 2Mbp bin widths). The heatmaps and Shannon diversity plots are really where the range and size of the centromeres can be determined with more precision, if there are patterns visible. Take a look at the heatmaps, histograms and Shannon diversity plots. Are there clear patterns in these plots? Could you share a couple example plots here or email them to me? For some genomes, perhaps because the assemblies are incomplete or because the genomes do not contain clear tandem repeats it can be difficult to get a more accurate position than the 2Mbp range around the predicted position in the text file.

**Comment by frwjo** [comment]
Hi,thank you for your answer;
Actually,I dont't think my genome which is  incomplete,but there may  contain clear tandem repeats,just your say.And I think that they are Retrotransposon.
![eggplant_H0-AT_Chr12_All_spec_bp35_2000seq1_19316TRUE](https://github.com/celphin/RepeatOBserverV1/assets/157588867/591b1e10-8122-4ec4-96cd-e2de46a8e369)
![eggplant_H0-AT_Chr12_roll_mean_Shannon_250](https://github.com/celphin/RepeatOBserverV1/assets/157588867/c8ae1ada-0d5f-4f1c-8d33-ff92d55b1817)

**Comment by celphin** [comment]
Thanks for posting the images. The pattern at 35Mbp in the chromosome above looks very similar to the known centromeres made of transposons in wheat and corn. The clearer tandem repeats at the edges of the chromosome are likely subtelomeric repeats (similar to those seen in Brassica and many other genomes). In the 165 chromosomes that I explored with known centromeres, blurs of transposable elements like you see at 35Mbp were only ever associated with centromere positions. However, this species could be an exception. The pattern in the heatmap looks to extend from about 34-37Mbp if you want a range. Overall the positions in the histograms text file have approx 2Mbp on either side.
