### ISSUE TITLE
Understanding y-axis of the heatmap plots

### ISSUE THREAD

**Issue by Jokendo-collab** [celphin/RepeatOBserverV1#7]
I am trying to understand and explain the heatmap figures. I can see what is the difference in  `1/2500` and `1/71` ? This is not well captured in the preprint and I was wondering is you can help explain the below figure: What the color scale mean and more specifically  how to make sense of the y-axis

![Screenshot 2024-06-25 at 10 47 24 AM](https://github.com/celphin/RepeatOBserverV1/assets/26459707/b2342792-bb6b-4fca-97c2-c166309773be)

**Comment by celphin** [comment]
Hi, 

Thanks for asking for clarification on this. The colour scale axis shows relative values that have no physical meaning and are there specifically for visualizing the Fourier transforms. The scale is based on the mean and SD of the whole chromosome’s normalized 5kbp Fourier transforms. Some scaling was done to make high repeat abundances show up clearly  in the plots and make low repeat abundances not swamp the plots. The colour scale max values go up to 6SD above the mean repeat Fourier abundance while the min colour is 0.8SD below the mean. This results in the regular blue background ‘noise’ for values below the mean and clear bright yellow/green strips where there are abundant repeats over the mean. 

What we call the Fourier repeat abundances are also relative values without clear biological meaning. They are not a count of the number of repeating sequences. If you want the number of repeats in a clearly repeating tandem sequence, try running this script:
[https://github.com/celphin/RepeatOBserverV1#finding-repeat-sequences](https://github.com/celphin/RepeatOBserverV1#finding-repeat-sequences) 
A higher repeat abundance in the Fourier transform (say 20) means more repeats in that window of that length than a value of 5 but does not mean 20 repeating sequences in that window. 

The exact calculations after running the fast fourier transform in R are:
First, normalize the fourier transform: norm_fft = 2\*mod(fft)
Second, scale the output to deal with aliasing in Fourier transforms:
(each_rep_abund/rep_length)^1.2 
Aliasing occurs for long repeats that are close to the window length (5kbp). This repeats appear to have higher abundances because of this effect, not because they actually are occurring more frequently in the genome. Thus we divide the repeat abundance by the repeat length to minimize this effect in the longer repeat lengths. 
Finally to adjust the colour scales for visualization in the heatmap plots (determined using trial and error for colours in R): 
zmintot<-zmeantot-(0.8\*zsd)+2 # same colour for everything ~1SD less than the mean
zmaxtot<-zmeantot+(6\*zsd)-3  # want values greater than the mean to have a wider range of colours

Best wishes,
Cassandra
