### ISSUE TITLE
Summary figures do not contain the largest chromosomes

### ISSUE THREAD

**Issue by smile4life** [celphin/RepeatOBserverV1#9]
Hi!

Sorry to bother you, but I was hoping for some support. RepeatOBserverV1 seems to finish, producing output for the smaller chromosomes, but doesn't generate summary output files for the largest chromosomes. I've been digging around in the output files trying to figure out how to create the summary output myself, but I'm struggling to identify which files to use in making a plot similar to the summary histogram. 

More simply, the centromere histogram output by the software only contains 3 of the expected 6 chromosomes (as well as an "NA" panel). The chromosomes that are missing are the largest. I'd really appreciate help with plotting the missing chromosomes!

Thanks for making this cool programme!
Zoë

**Comment by celphin** [comment]
Hi Zoë,

How large are the large chromosomes that are not running? Can you post here what the output directory structure looks like?
```
cd  output_folder/SPP_Hap/Summary_output
tree
```
I will take a look at this tomorrow in more detail.
Best wishes,
Cassandra

**Comment by smile4life** [comment]
Hi Cassandra!

The chromosomes that aren't running are 465 Mb, 5 Mb, and 503 Mb (I think - there's a ~400 Mb NA panel in the final figure and the chromosome_renaming.txt file included a small 5 Mb scaffold that didn't appear in the final figure). The 329 Mb, 222 Mb, and 179 Mb chromosomes worked great!

This is the tree output: [tree.txt](https://github.com/user-attachments/files/16753266/tree.txt)

I didn't use slurm, but I piped the programme's output to this file: [out.TXpat.txt](https://github.com/user-attachments/files/16753276/out.TXpat.txt) . I didn't see any errors after EMBOSS tried to run.

Thanks so much for your help!!
Zoë

**Comment by celphin** [comment]
Hi Zoe,

Thanks for pointing this out. The issue with plotting the summary files for the larger chromosomes should be fixed now. The program splits the >400Mbp chromosomes into parts since there were memory issues for any chromosomes >400Mbp. Since chromosomes this large are somewhat rare I had forgotten to rejoin them in the summary plots. 

You do not need to rerun the whole program. You should be able to get the plots now by running the following in R. 

```
# reinstall the new version of the code - I made a couple changes to rejoin large chromosome parts
library(devtools)
install_github("celphin/RepeatOBserverV1") #to install the package
library(RepeatOBserverV1)

# you may need to change the paths here
inpath="~/scratch/repeats/input_chromosomes"
outpath="~/scratch/repeats/output_chromosomes"
fname="TXpat_H2-CG"

plot_all_chromosomes(fname=fname, inpath=inpath, outpath=outpath)
roll_sum_histogram(fname=fname, outpath=outpath)
```

A couple other points that I noticed. You are running the CG version  - although it should not make a difference, you could also run the more standard AT version. Centromeric repeats are often AT dominated so for very small repeats you might get a slightly better result in AT. Also, the 5Mbp chromosome will not work with the histograms/repeat abundance plots since the windows used are too close to the size of the chromosome. Finally, the repeat abundance plots and centromere ranges are new but give a more accurate estimate of the whole centromeric region.

Please let me know if you run into any issues with the above.

Best wishes,
Cassandra
